global:
  kubernetes:
    versions: {}
    upstreamVersions:
      include: false

name: hcloud
enabled: true
kubernetes:
  versions: {}

machineImages:
  - name: ubuntu
    versions:
    - version: 20.4.20210616
      cri:
      - name: containerd
machineTypes:
  - name: cx22
    cpu: "2"
    memory: 4Gi
    gpu: "0"
  - name: cpx21
    cpu: "3"
    memory: 4Gi
    gpu: "0"
  - name: cx32
    cpu: "4"
    memory: 8Gi
    gpu: "0"
  - name: cpx31
    cpu: "4"
    memory: 8Gi
    gpu: "0"
  - name: cx42
    cpu: "8"
    memory: 16Gi
    gpu: "0"
  - name: cpx41
    cpu: "8"
    memory: 16Gi
    gpu: "0"
  - name: cx52
    cpu: "16"
    memory: 32Gi
    gpu: "0"
  - name: cpx51
    cpu: "16"
    memory: 32Gi
    gpu: "0"
  - name: ccx13
    cpu: "2"
    memory: 8Gi
    gpu: "0"
  - name: ccx23
    cpu: "4"
    memory: 16Gi
    gpu: "0"
  - name: ccx33
    cpu: "8"
    memory: 32Gi
    gpu: "0"
  - name: ccx43
    cpu: "16"
    memory: 64Gi
    gpu: "0"
  - name: ccx53
    cpu: "32"
    memory: 128Gi
    gpu: "0"
  - name: ccx63
    cpu: "48"
    memory: 192Gi
    gpu: "0"
  - name: cax11
    cpu: "2"
    memory: 4Gi
    gpu: "0"
    architecture: arm64
  - name: cax21
    cpu: "4"
    memory: 8Gi
    gpu: "0"
    architecture: arm64
  - name: cax31
    cpu: "8"
    memory: 16Gi
    gpu: "0"
    architecture: arm64
  - name: cax41
    cpu: "16"
    memory: 32Gi
    gpu: "0"
    architecture: arm64
regions:
  - name: hel1
    zones:
      - name: hel1-dc2
  - name: fsn1
    zones:
      - name: fsn1-dc14
  - name: nbg1
    zones:
      - name: nbg1-dc3
  - name: ash
    zones:
      - name: ash-dc1
        unavailableMachineTypes:
        - cx22
        - cx32
        - cx42
        - cx52
        - cax11
        - cax21
        - cax31
        - cax41
  - name: hil
    zones:
      - name: hil-dc1
        unavailableMachineTypes:
        - cx22
        - cx32
        - cx42
        - cx52
        - cax11
        - cax21
        - cax31
        - cax41
  - name: sin
    zones:
      - name: sin-dc1
        unavailableMachineTypes:
        - cx22
        - cx32
        - cx42
        - cx52
        - cax11
        - cax21
        - cax31
        - cax41
providerConfig:
  apiVersion: hcloud.provider.extensions.gardener.cloud/v1alpha1
  kind: CloudProfileConfig
  defaultStorageFsType: ext4
  machineImages:
  - name: ubuntu
    versions:
    - version: 20.4.20210616
      imageName: ubuntu-20.04
  regions:
    - name: hel1
    - name: fsn1
    - name: nbg1
    - name: ash
