global:
  kubernetes:
    versions: {}
    upstreamVersions:
      include: false

name: hcloud
enabled: true
kubernetes:
  versions: {}

machineImages:
  - name: ubuntu
    versions:
    - version: 24.4.20240529
      cri:
      - name: containerd
machineTypes:
  - name: cpx12
    cpu: "1"
    memory: 2Gi
    gpu: "0"
  - name: cx23
    cpu: "2"
    memory: 4Gi
    gpu: "0"
  - name: cpx22
    cpu: "2"
    memory: 4Gi
    gpu: "0"
  - name: cx33
    cpu: "4"
    memory: 8Gi
    gpu: "0"
  - name: cpx32
    cpu: "4"
    memory: 8Gi
    gpu: "0"
  - name: cx43
    cpu: "8"
    memory: 16Gi
    gpu: "0"
  - name: cpx42
    cpu: "8"
    memory: 16Gi
    gpu: "0"
  - name: cx53
    cpu: "16"
    memory: 32Gi
    gpu: "0"
  - name: cpx52
    cpu: "12"
    memory: 24Gi
    gpu: "0"
  - name: cpx62
    cpu: "16"
    memory: 32Gi
    gpu: "0"
  - name: ccx13
    cpu: "2"
    memory: 8Gi
    gpu: "0"
  - name: ccx23
    cpu: "4"
    memory: 16Gi
    gpu: "0"
  - name: ccx33
    cpu: "8"
    memory: 32Gi
    gpu: "0"
  - name: ccx43
    cpu: "16"
    memory: 64Gi
    gpu: "0"
  - name: ccx53
    cpu: "32"
    memory: 128Gi
    gpu: "0"
  - name: ccx63
    cpu: "48"
    memory: 192Gi
    gpu: "0"
  - name: cax11
    cpu: "2"
    memory: 4Gi
    gpu: "0"
    architecture: arm64
  - name: cax21
    cpu: "4"
    memory: 8Gi
    gpu: "0"
    architecture: arm64
  - name: cax31
    cpu: "8"
    memory: 16Gi
    gpu: "0"
    architecture: arm64
  - name: cax41
    cpu: "16"
    memory: 32Gi
    gpu: "0"
    architecture: arm64
regions:
  - name: hel1
    zones:
      - name: hel1-dc2
  - name: fsn1
    zones:
      - name: fsn1-dc14
  - name: nbg1
    zones:
      - name: nbg1-dc3
  - name: ash
    zones:
      - name: ash-dc1
        unavailableMachineTypes:
        - cx23
        - cx33
        - cx43
        - cx53
        - cax11
        - cax21
        - cax31
        - cax41
  - name: hil
    zones:
      - name: hil-dc1
        unavailableMachineTypes:
        - cx23
        - cx33
        - cx43
        - cx53
        - cax11
        - cax21
        - cax31
        - cax41
  - name: sin
    zones:
      - name: sin-dc1
        unavailableMachineTypes:
        - cx23
        - cx33
        - cx43
        - cx53
        - cax11
        - cax21
        - cax31
        - cax41
providerConfig:
  apiVersion: hcloud.provider.extensions.gardener.cloud/v1alpha1
  kind: CloudProfileConfig
  defaultStorageFsType: ext4
  machineImages:
  - name: ubuntu
    versions:
    - version: 24.4.20240529
      imageName: ubuntu-24.04
  regions:
    - name: hel1
    - name: fsn1
    - name: nbg1
    - name: ash
